### ISSUE TITLE
Unable to create new JFrog environement for use with extension 

### ISSUE THREAD

**Issue by ericsmalling** [jfrog/jfrog-docker-desktop-extension#102]
Clicking the "Create one for FREE" link takes me to the account creation page but once I complete it, it says I can go back to Docker Desktop to continue but it never gets past the "Docker Desktop will automatically connect to your environment once the setup is complete" message.

Tried with two different accounts (one using Google SSO, the other with an email+password).

**Comment by eyalk007** [comment]
Hi @ericsmalling ,
The newest version of the plugin (1.3.0) supports opening an environment with a free trial.
Please update if you are experiencing any issues (:
