### ISSUE TITLE
Showing scan errors with Docker Desktop API

### ISSUE THREAD

**Issue by asafgabai** [jfrog/jfrog-docker-desktop-extension#57]
Instead of popping an alert in case of scan error, use Docker Desktop API to show an error notification.
Read more here: https://docs.docker.com/desktop/extensions-sdk/dev/api/dashboard/
This API is already used in the settings and welcome pages.
It's highly recommended to do this issue after resolving issue #56, because showing the current log errors in a notification will look even worse than it looks now.

**Comment by eigengravy** [comment]
hi, i would love to work on this

**Comment by sverdlov93** [comment]
Hi @eigengravy, the above enhancement was actually part of our latest release and all our app errors are forwarded to the Docker Desktop toast API. 
Of course, we would appreciate any contribution with improvements to our error mechanism or any other section of the code or the app.
