### ISSUE TITLE
Login to jfrog extension with docker desktop

### ISSUE THREAD

**Issue by raksp** [jfrog/jfrog-docker-desktop-extension#85]
When i try to login to the jfrog extension on Docker Desktop i get the message 'C:\User\{username} is not recognised as an internal or external command, operable program or batch file'. This happens whether i am using a basic using my username and password for Jfrog or when i obtain an access token from JFrog and use the access token.  Is there a bug in the extension? or is it something i am doing wrong
![JFrog](https://user-images.githubusercontent.com/19364375/189612125-e400614d-80d9-4b2f-a36b-14198d02841e.JPG)

**Comment by sverdlov93** [comment]
Hi @raksp,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
Can you provide your OS and Docker Desktop Extension version?
Also, Can you share the latest logs under /users/<user>/.jfrog-docker-desktop-extension/logs?

**Comment by sverdlov93** [comment]
@raksp thanks!
Can you also provide the docker info using 'docker version' command?

**Comment by raksp** [comment]
Error response from daemon: Bad response from Docker engine
Client:
Cloud integration: v1.0.29
Version: 20.10.17
API version: 1.41
Go version: go1.17.11
Git commit: 100c701
Built: Mon Jun 6 23:09:02 2022
OS/Arch: windows/amd64
Context: default
Experimental: true

**Comment by sverdlov93** [comment]
@raksp , Looks like your docker daemon is down.
Can you try starting/restarting it?

**Comment by raksp** [comment]
Restarted



C:\Program Files\Docker\Docker\resources>docker version
Client:
Cloud integration: v1.0.29
Version: 20.10.17
API version: 1.41
Go version: go1.17.11
Git commit: 100c701
Built: Mon Jun 6 23:09:02 2022
OS/Arch: windows/amd64
Context: default
Experimental: true
Server: Docker Desktop 4.12.0 (85629)
Engine:
Version: 20.10.17
API version: 1.41 (minimum version 1.12)
Go version: go1.17.11
Git commit: a89b842
Built: Mon Jun 6 23:01:23 2022
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.6.8
GitCommit: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
runc:
Version: 1.1.4
GitCommit: v1.1.4-0-g5fd4c4d
docker-init:
Version: 0.19.0
GitCommit: de40ad0
Kubernetes:
Version: Unknown
StackAPI: Unknown
C:\Program Files\Docker\Docker\resources>

**Comment by sverdlov93** [comment]
Is the extension still not working after the restart?

**Comment by raksp** [comment]
No, still errors with the same message 'C:\User{username} is not recognised as an internal or external command, operable program or batch file'

**Comment by raksp** [comment]
Error response from daemon: Bad response from Docker engine
Client:
Cloud integration: v1.0.29
Version: 20.10.17
API version: 1.41
Go version: go1.17.11
Git commit: 100c701
Built: Mon Jun 6 23:09:02 2022
OS/Arch: windows/amd64
Context: default
Experimental: true

**Comment by mambroziak** [comment]
Was this ever resolved? I'm having the same issue.

**Comment by eyalk007** [comment]
Hello everyone,
thank you for all the feedback!
We have solved this issue, and will release the fix in the next release cycle😊
