### ISSUE TITLE
Failed running command due to docker executable not found

### ISSUE THREAD

**Issue by aquacode** [jfrog/jfrog-docker-desktop-extension#92]
I am able to run `jf docker scan` on command line, docker desktop seems to run fine as I'm able to run many other containers, etc.

However, using Docker Desktop with JFrog extension I am getting the following error:

09:37:38 [Error] failed running command ... with error: exec: "docker": executable file not found in $PATH

Yet, `docker` runs on my command line find and the path to it is included in my $PATH variable.

macOS Ventura 13.3.1
Apple M2 Max
Docker Desktop v4.19.0
JFrog extension v1.2.1
Xray Version: 3.73.5
CLI Version: 2.25.1

**Comment by sverdlov93** [comment]
Hi @aquacode and @thechane 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
The issue was caused by Docker Desktop version and the next Docker Desktop version should fix that.

**Comment by aquacode** [comment]
Works after updating Docker Desktop to version 4.20
