### ISSUE TITLE
Error when using JFrog Xray Scan in Docker Desktop

### ISSUE THREAD

**Issue by akkadaya** [jfrog/jfrog-docker-desktop-extension#95]
When I scan an image using JFrog Xray Scan in Docker Desktop I get these error banners:

<img width="664" alt="image" src="https://github.com/jfrog/jfrog-docker-desktop-extension/assets/1834445/1bb0cb12-b7fe-49ed-b145-d56985e6d7c8">

When checking the logs I have this:

```sh
11:05:49 [Info] Creating image archive...
11:05:49 [Error] failed running command: 'docker save bridgecrew/checkov:latest -o /var/folders/1z/18hkqblx4gj8cw08xkpnfw180000gq/T/jfrog.cli.temp.-1684631149-3754232923/image.tar' with error: exec: "docker": executable file not found in $PATH - 
```

The output of
```sh
which -a docker
# Output
/usr/local/bin/docker
```

I'm using 
OS: MacOS Ventura 13.3.1

_From JFrog Docker extension settings_
Xray: 3.73.8
CLI: 2.25.1

**Comment by akkadaya** [comment]
Duplicate of #92

**Comment by sverdlov93** [comment]
Hi @akkadaya 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
The issue was caused by Docker Desktop version and the next Docker Desktop version should fix that.
